### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ericsimandle** [sjevelazco/flexsdm#266]
the rest of my libraries are updated, but I get the following error.

> devtools::install_github('sjevelazco/flexsdm')
Downloading GitHub repo sjevelazco/flexsdm@HEAD
✓  checking for file ‘/tmp/RtmpDagyjX/remotes1c3fe0498f/sjevelazco-flexsdm-aaa7271/DESCRIPTION’ ...
─  preparing ‘flexsdm’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘flexsdm_0.0.2.tar.gz’
   
Installing package into ‘/home/eric/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘flexsdm’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: package slot missing from signature for generic ‘coerce’
and classes Raster, SpatRaster
cannot use with duplicate class names (the package may need to be re-installed)
Execution halted
ERROR: lazy loading failed for package ‘flexsdm’
* removing ‘/home/eric/R/x86_64-pc-linux-gnu-library/4.1/flexsdm’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpDagyjX/file1c3f6dd11570/flexsdm_0.0.2.tar.gz’ had non-zero exit status

sessionInfo:  
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.2

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libmkl_rt.so

**Comment by sjevelazco** [comment]
The problem is the last version of [terra](https://github.com/rspatial/terra/issues/443). So, please, first install the development version of terra  https://github.com/rspatial/terra and then flexsdm.
