### ISSUE TITLE
occfilt_env

### ISSUE THREAD

**Issue by JoelMet** [sjevelazco/flexsdm#313]
Hi, 
I tested the occfilt_env function and found out that it fails when environmental variables are rare. Within the function zero values are then produced which cause an error message: 
```
Error in seq.default(ext1[1], ext1[2], by = res[i]) : 
  invalid '(to - from)/by'
```

As far as i can see the error occures in this part of the function code:
```
 n <- ncol(env_layer)
 res <- res <- apply(env_layer, 2, function(x) diff(range(x))) / nbins
for (i in 1:n) {
    ext1 <- range(env_layer[, i])
    ext1[2] <- ext1[2] + 0.05
    ext1 <- c(ext1[1] - 0.000001, ext1[2] + 0.000001)
    classes[[i]] <- seq(ext1[1], ext1[2], by = res[i])
    classes[[i]][length(classes[[i]])] <- ext1[2]
  }
```
I realized that one of my environmental variables produces a zero in `res[i]` so that the seq function does not work.

Is there any solution for this problem?

**Comment by sjevelazco** [comment]
Please, can you provide this variable so I can reproduce this error?  Thanks
