### ISSUE TITLE
Predicting PCA

### ISSUE THREAD

**Issue by wevertonbio** [sjevelazco/flexsdm#334]
Hello Santiago Velazco,

Firstly, I would like to congratulate you on the package. Besides being very useful, it is also very didactic. I always recommend the package's website to those who are starting to study niche modeling.

My question is about the projection of PCA in various scenarios. To demonstrate my point, I ran the correct_colinvar function with temperature variables from WorldClim cropped to the state of Paraná (Brazil). The coefficients on the first axis show that temperature variables (Bio11, Bio06, Bio01) have negative values.

```
   variable      PC1
1 Bio01    -0.452  
2 Bio02    -0.100  
3 Bio03    -0.177  
4 Bio04     0.135  
5 Bio05    -0.412  
6 Bio06    -0.415  
7 Bio07     0.00865
8 Bio10    -0.439  
9 Bio11    -0.449
```
As a result, we can expect warmer locations to have lower score values on the first axis. When we plot the map, we can see that the warmer regions in Paraná have lower ("more negatives") values:
![image](https://github.com/sjevelazco/flexsdm/assets/90938238/80447206-b011-4449-9063-4ab0b73a2cd6)

So, if we project this PCA to a warmer future, the expected scores should be lower. However, the function returns a scenario with higher scores:
![image](https://github.com/sjevelazco/flexsdm/assets/90938238/360d1688-eb6e-486c-85b0-c5ec1cbc9878)

This happens, I believe, because [you use the function terra::scale](https://github.com/sjevelazco/flexsdm/blob/120f7de4e0a0fde2134c3ce25676210237fee190/R/correct_colinvar.R#L322) to scale the variables from the new scenario before predicting. 

When we predict the PCA without scaling the variables, we get a map that appears to make more sense, with lower predicted scores in the warmer scenario.
![image](https://github.com/sjevelazco/flexsdm/assets/90938238/65f4951a-b350-44f0-bf16-73a5871c1099)

I also tested the PCA prediction with the kuenm_rpca function from the kuenm package, and the results are identical as when the variables are not scaled before predicting:
![image](https://github.com/sjevelazco/flexsdm/assets/90938238/055dcf9c-0bbb-48b0-9fbe-001e37179880)

So I was wondering if it is actually required to scale the variables of the new scenario before predicting, because the predictions without scale appear to make more sense to me.

If you want to reproduce the results, I've attached the files and code I used. 
[PCA_flexsdm.zip](https://github.com/sjevelazco/flexsdm/files/11777242/PCA_flexsdm.zip)

**Comment by sjevelazco** [comment]
Hi Weverton 

Thank you so much for pointing out this issue. I fixed this problem. Now variable standardization is made explicitly outside the `prcomp` function. It is important to standardize projection data (past or present) based on mean and sd of reference data (current conditions) used to construct the PCA. 

Thanks
