### ISSUE TITLE
response curves

### ISSUE THREAD

**Issue by fernandabiologia** [sjevelazco/flexsdm#346]
I've just started using flex sdm, such a great package. Thanks for creating it. 

I was wondering if there is a way to extract response curves for the predictors in the different models. I couldn't find anywhere in the package documentation or vignettes.

Thanks.

**Comment by sjevelazco** [comment]
Hi 
Thank you. It is possible to construct response curves using the:
[p_pdp](https://sjevelazco.github.io/flexsdm/reference/p_pdp.html) # for plotting
[p_bpdp](https://sjevelazco.github.io/flexsdm/reference/p_bpdp.html) # for plotting
[data_pdp](https://sjevelazco.github.io/flexsdm/reference/data_pdp.html) # for getting a tibble object
[data_bpdp](https://sjevelazco.github.io/flexsdm/reference/data_bpdp.html) # for getting a tibble object
 Also take a look [this vignette](https://sjevelazco.github.io/flexsdm/articles/v06_Extrapolation_example.html)
