### ISSUE TITLE
correct_colinvar() for pearson method do not return 3 objects, only 2 objects

### ISSUE THREAD

**Issue by ManuelSpinola** [sjevelazco/flexsdm#354]
In the website you stated that for the function correct_colinvar() using the pearson method return 3 objects, being a SpatRaster the first one, but I cannot retrieve this first object, only 2 objects.

somevar <- system.file("external/somevar.tif", package = "flexsdm")

somevar <- terra::rast(somevar)

var <- correct_colinvar(env_layer = somevar, method = c("pearson", th = "0.7"))

**Comment by sjevelazco** [comment]
Hi 
Thank you for your comment. However, the website is correct, it is stated that when used the pearson method function returns two objects. 
https://sjevelazco.github.io/flexsdm/reference/correct_colinvar.html?q=correct_colinvar#value
