### ISSUE TITLE
Survey data bias grid example?

### ISSUE THREAD

**Issue by darrennorris** [sjevelazco/flexsdm#368]
Thank you so much for this wonderful package.
I would like to include a bias grid in a modelling workflow as suggested by Elith et. al. 2011.
Is there functionality to explicitly include a bias grid that indicates the biases in the survey data for all algorithms?
There is an example in the MaxEnt tutorial, but I cannot understand how to implement this more generally in flexsdm.
If it is possible, I would like to ask if it could be added as a vignette showing how.
Many thanks,
Darren
Elith et. al. 2011. A statistical explanation of MaxEnt for ecologists.  https://doi.org/10.1111/j.1472-4642.2010.00725.x
I know this isssue can be controlled to a certain extent by 
i) chosing appprate resolution (extent and cell size), 
ii) chosing appropriate pseudo-absences
iii) environmental filtering of observation data

**Comment by sjevelazco** [comment]
Hi Darren 

You can create a bias grid and use it to sample background points. However, these biased background points will be used only for the Maxent algorithm. As far as I know, such biased background points biased grid are not used in other algorithms like SVM, RF, GAM, etc. So, I should not advise if it improves the model or turns worse. 
In case you want to use environmental or geographical filtering approach for occurrences, in flexsdm are the  functions occfilt_env() and occfilt_geo() 
Best
